title: Australasian Document Computing Symposium
description: Details of the Australasian Document Computing Symposium.
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
